#!/usr/bin/bash

URGENT_VALUE=1
PACKAGE_COUNT=$(checkupdates | wc -l)

if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
  echo "${PACKAGE_COUNT}"
  echo ""
  #if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
  	#echo "\e[0;33m ${PACKAGE_COUNT} \e[m"
  	#echo ""
    #exit 33
  #fi
fi
