#!/bin/bash
#----------------------------------------------------------------------------------------------------
#Mouse actions for the block
case $BLOCK_BUTTON in
	3) pamixer -t ;;
	4) pamixer -i 5 ;;
	5) pamixer -d 5 ;;
esac

#Toggle mute -n
[[ $(pamixer --get-mute) = "true" ]] && echo  && exit
#Display volume
echo  $(pamixer --get-volume)%;
